// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "features/board.mdx": () => import("../content/docs/features/board.mdx?collection=docs"), "features/cashier.mdx": () => import("../content/docs/features/cashier.mdx?collection=docs"), "features/overview.mdx": () => import("../content/docs/features/overview.mdx?collection=docs"), "features/products.mdx": () => import("../content/docs/features/products.mdx?collection=docs"), "features/reports.mdx": () => import("../content/docs/features/reports.mdx?collection=docs"), "features/stock.mdx": () => import("../content/docs/features/stock.mdx?collection=docs"), "features/store-setup.mdx": () => import("../content/docs/features/store-setup.mdx?collection=docs"), "getting-started/edu-mode.mdx": () => import("../content/docs/getting-started/edu-mode.mdx?collection=docs"), "getting-started/introduction.mdx": () => import("../content/docs/getting-started/introduction.mdx?collection=docs"), "getting-started/quick-start.mdx": () => import("../content/docs/getting-started/quick-start.mdx?collection=docs"), "getting-started/setup-wizard.mdx": () => import("../content/docs/getting-started/setup-wizard.mdx?collection=docs"), "getting-started/what-is-fibidy.mdx": () => import("../content/docs/getting-started/what-is-fibidy.mdx?collection=docs"), "settings/account.mdx": () => import("../content/docs/settings/account.mdx?collection=docs"), "settings/contact.mdx": () => import("../content/docs/settings/contact.mdx?collection=docs"), "settings/discounts.mdx": () => import("../content/docs/settings/discounts.mdx?collection=docs"), "settings/hero.mdx": () => import("../content/docs/settings/hero.mdx?collection=docs"), "settings/highlights.mdx": () => import("../content/docs/settings/highlights.mdx?collection=docs"), "settings/overview.mdx": () => import("../content/docs/settings/overview.mdx?collection=docs"), "settings/promos.mdx": () => import("../content/docs/settings/promos.mdx?collection=docs"), "settings/social.mdx": () => import("../content/docs/settings/social.mdx?collection=docs"), "settings/trading-mode.mdx": () => import("../content/docs/settings/trading-mode.mdx?collection=docs"), "subscription/overview.mdx": () => import("../content/docs/subscription/overview.mdx?collection=docs"), "subscription/payment.mdx": () => import("../content/docs/subscription/payment.mdx?collection=docs"), "subscription/pricing.mdx": () => import("../content/docs/subscription/pricing.mdx?collection=docs"), "studio/overview.mdx": () => import("../content/docs/studio/overview.mdx?collection=docs"), "studio/templates.mdx": () => import("../content/docs/studio/templates.mdx?collection=docs"), "troubleshooting/common-issues.mdx": () => import("../content/docs/troubleshooting/common-issues.mdx?collection=docs"), "troubleshooting/offline.mdx": () => import("../content/docs/troubleshooting/offline.mdx?collection=docs"), }),
};
export default browserCollections;