// @ts-nocheck
import { default as __fd_glob_65 } from "../content/docs/working-with-the-codebase/meta.json?collection=meta"
import { default as __fd_glob_64 } from "../content/docs/setup/meta.json?collection=meta"
import { default as __fd_glob_63 } from "../content/docs/push-notification/meta.json?collection=meta"
import { default as __fd_glob_62 } from "../content/docs/landing/meta.json?collection=meta"
import { default as __fd_glob_61 } from "../content/docs/email/meta.json?collection=meta"
import { default as __fd_glob_60 } from "../content/docs/configuration/meta.json?collection=meta"
import { default as __fd_glob_59 } from "../content/docs/commerce/meta.json?collection=meta"
import { default as __fd_glob_58 } from "../content/docs/deployment/meta.json?collection=meta"
import { default as __fd_glob_57 } from "../content/docs/database/meta.json?collection=meta"
import { default as __fd_glob_56 } from "../content/docs/authentication/meta.json?collection=meta"
import { default as __fd_glob_55 } from "../content/docs/architecture/meta.json?collection=meta"
import { default as __fd_glob_54 } from "../content/docs/analytics/meta.json?collection=meta"
import { default as __fd_glob_53 } from "../content/docs/meta.json?collection=meta"
import * as __fd_glob_52 from "../content/docs/working-with-the-codebase/update-the-codebase.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/working-with-the-codebase/project-structure.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/working-with-the-codebase/manage-dependencies.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/setup/tooling.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/setup/supabase.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/setup/resend.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/setup/project.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/setup/introduction.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/push-notification/setup.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/push-notification/sending-notifications.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/push-notification/overview.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/landing/overview.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/landing/legal-pages.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/landing/customization.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/email/templates.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/email/setup.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/email/overview.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/deployment/vercel.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/deployment/self-hosted.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/deployment/checklist.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/database/type-definitions.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/database/schema-migration.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/database/overview.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/configuration/permissions.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/configuration/overview.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/configuration/branding.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/configuration/app-config.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/commerce/webhooks.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/commerce/subscriptions.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/commerce/setup.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/commerce/products.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/commerce/overview.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/commerce/orders.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/commerce/customers.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/commerce/checkout.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/authentication/overview.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/authentication/magic-link.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/authentication/google-oauth.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/authentication/email-password.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/authentication/apple-oauth.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/authentication/adding-oauth-providers.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/architecture/overview.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/architecture/module-system.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/analytics/usage.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/analytics/setup.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/analytics/overview.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/troubleshooting.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/tech-stack.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/monitoring.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/internationalization.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/environment-variables.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/activity-logging.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.doc("docs", "content/docs", {"activity-logging.mdx": __fd_glob_0, "environment-variables.mdx": __fd_glob_1, "index.mdx": __fd_glob_2, "internationalization.mdx": __fd_glob_3, "monitoring.mdx": __fd_glob_4, "tech-stack.mdx": __fd_glob_5, "troubleshooting.mdx": __fd_glob_6, "analytics/overview.mdx": __fd_glob_7, "analytics/setup.mdx": __fd_glob_8, "analytics/usage.mdx": __fd_glob_9, "architecture/module-system.mdx": __fd_glob_10, "architecture/overview.mdx": __fd_glob_11, "authentication/adding-oauth-providers.mdx": __fd_glob_12, "authentication/apple-oauth.mdx": __fd_glob_13, "authentication/email-password.mdx": __fd_glob_14, "authentication/google-oauth.mdx": __fd_glob_15, "authentication/magic-link.mdx": __fd_glob_16, "authentication/overview.mdx": __fd_glob_17, "commerce/checkout.mdx": __fd_glob_18, "commerce/customers.mdx": __fd_glob_19, "commerce/orders.mdx": __fd_glob_20, "commerce/overview.mdx": __fd_glob_21, "commerce/products.mdx": __fd_glob_22, "commerce/setup.mdx": __fd_glob_23, "commerce/subscriptions.mdx": __fd_glob_24, "commerce/webhooks.mdx": __fd_glob_25, "configuration/app-config.mdx": __fd_glob_26, "configuration/branding.mdx": __fd_glob_27, "configuration/overview.mdx": __fd_glob_28, "configuration/permissions.mdx": __fd_glob_29, "database/overview.mdx": __fd_glob_30, "database/schema-migration.mdx": __fd_glob_31, "database/type-definitions.mdx": __fd_glob_32, "deployment/checklist.mdx": __fd_glob_33, "deployment/self-hosted.mdx": __fd_glob_34, "deployment/vercel.mdx": __fd_glob_35, "email/overview.mdx": __fd_glob_36, "email/setup.mdx": __fd_glob_37, "email/templates.mdx": __fd_glob_38, "landing/customization.mdx": __fd_glob_39, "landing/legal-pages.mdx": __fd_glob_40, "landing/overview.mdx": __fd_glob_41, "push-notification/overview.mdx": __fd_glob_42, "push-notification/sending-notifications.mdx": __fd_glob_43, "push-notification/setup.mdx": __fd_glob_44, "setup/introduction.mdx": __fd_glob_45, "setup/project.mdx": __fd_glob_46, "setup/resend.mdx": __fd_glob_47, "setup/supabase.mdx": __fd_glob_48, "setup/tooling.mdx": __fd_glob_49, "working-with-the-codebase/manage-dependencies.mdx": __fd_glob_50, "working-with-the-codebase/project-structure.mdx": __fd_glob_51, "working-with-the-codebase/update-the-codebase.mdx": __fd_glob_52, });

export const meta = await create.meta("meta", "content/docs", {"meta.json": __fd_glob_53, "analytics/meta.json": __fd_glob_54, "architecture/meta.json": __fd_glob_55, "authentication/meta.json": __fd_glob_56, "database/meta.json": __fd_glob_57, "deployment/meta.json": __fd_glob_58, "commerce/meta.json": __fd_glob_59, "configuration/meta.json": __fd_glob_60, "email/meta.json": __fd_glob_61, "landing/meta.json": __fd_glob_62, "push-notification/meta.json": __fd_glob_63, "setup/meta.json": __fd_glob_64, "working-with-the-codebase/meta.json": __fd_glob_65, });